### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by in-a-days** [fewieden/MMM-Mobile#1]
![error](https://cloud.githubusercontent.com/assets/24900913/21777382/724e402e-d653-11e6-831b-e0eab12c5a1d.jpg)

**Comment by in-a-days** [comment]
And these are the contents of the npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchNamedPackageData async
20 silly mapToRegistry name async
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry data Result {
23 silly mapToRegistry   raw: 'async',
23 silly mapToRegistry   scope: null,
23 silly mapToRegistry   escapedName: 'async',
23 silly mapToRegistry   name: 'async',
23 silly mapToRegistry   rawSpec: '',
23 silly mapToRegistry   spec: 'latest',
23 silly mapToRegistry   type: 'tag' }
24 silly mapToRegistry uri https://registry.npmjs.org/async
25 silly fetchNamedPackageData moment
26 silly mapToRegistry name moment
27 silly mapToRegistry using default registry
28 silly mapToRegistry registry https://registry.npmjs.org/
29 silly mapToRegistry data Result {
29 silly mapToRegistry   raw: 'moment',
29 silly mapToRegistry   scope: null,
29 silly mapToRegistry   escapedName: 'moment',
29 silly mapToRegistry   name: 'moment',

**Comment by fewieden** [comment]
looks like you have an incorrect config in line 263 can you check your config with http://jshint.com/?

**Comment by in-a-days** [comment]
You are correct!  Misplaced comma - just successfully installed.  Thank you!

**Comment by in-a-days** [comment]
Thank you for helping me resolve this.  I have a question about your app.  If I 'skip' out of the Modules/Config/Pairing introduction before scanning the QR code, is there any way to return to this prompt?  If I select 'skip' before pairing the devices it looks like I have to reinstall to find this option again.  Is this correct?  Thank you again!JB


-------- Original Message --------
Subject: Re: [fewieden/MMM-Mobile] Error during installation (#1)

**Comment by fewieden** [comment]
You can enter the tour on the side menu again
