### ISSUE TITLE
what is the name of the phone app I need?

### ISSUE THREAD

**Issue by justjim1220** [fewieden/MMM-Mobile#12]
I have found a couple MagicMirror apps in Google Play, but they aren't what I am looking for I guess. What I found is using MM on your phone, 

So, what is the name or any other info I need to get the right app?

**Comment by fewieden** [comment]
Hi Jim,

the app was never deployed to the Google PlayStore and iOS AppStore.

It remained a prototype. I sent you the app via email.

**Comment by justjim1220** [comment]
Interesting, I never received an email pertaining to the app.

Would you mind sending it again?

Thanks!

**Comment by fewieden** [comment]
Hi Jim, I sent the email today at ~5am utc timezone, did you also check your spam filter?

**Comment by justjim1220** [comment]
I have no idea what is going on with this but I still have not received an
email from you.

Try sending it to all 3 email addresses:
justjim1220@gmail.com
justjim1220@yahoo.com
jimandbobbi@hotmail.com
Apologies for the inconvenience.
