### ISSUE TITLE
app

### ISSUE THREAD

**Issue by rubenixnagios** [fewieden/MMM-Mobile#16]
any chance to get this prototype app??

Tx in advance & happy new year!!

can you send it over rubenixnagios [at] gmail [dot] com ?

**Comment by fewieden** [comment]
@rubenixnagios unfortunately Gmail is refusing emails with the app. Probably because it is an unsigned APK file. I can try to archive it and send it to you later.

**Comment by rubenixnagios** [comment]
cool, that would be nice.
maybe you can use wetransfer.com service...

Thanks so much!

**Comment by fewieden** [comment]
Sent
