### ISSUE TITLE
config.js reformatted after 'npm install'

### ISSUE THREAD

**Issue by in-a-days** [fewieden/MMM-Mobile#2]
After running npm install in the Modules/MMM-Mobile directory my config/config.js file is re-written.  The new config.js appears as a very long single line of text in nano.  Comments and formatting appear to have been removed.

**Comment by fewieden** [comment]
#3 the formatting will be fixed in the next version, but comments still will be missing

**Comment by in-a-days** [comment]
Resolved with update.  Thanks!
