### ISSUE TITLE
Resolved issue with reformating

### ISSUE THREAD

**Issue by lolobyte** [fewieden/MMM-Mobile#3]
Hi, thank you for this.

Very IMPORTANT!!!

As i put the Module “MMM-Mobile” at the very last module on the end of the config.js, all my module were started in a new order so that the modules was on different locations.

My config.js was modified like this sample:

/* Magic Mirror Config Sample * * By Michael Teeuw http://michaelteeuw.nl * MIT Licensed. */ var config = { port: 8080, // address: “192.168.178.45”, ipWhitelist: [ “127.0.0.1”, “::ffff:127.0.0.1”, “::1”, “::ffff:192.168.1.1/24”, ], language: ‘de’, timeFormat: 24, units: ‘metric’, modules: [ { module: ‘alert’, classes: ‘small bright’, // Add your own styling. Optional. disabled: false, }, { …

and so on. That means, the hole config structure was damaged and in one line.

Has anyone else this issue?

After restoring the old config.js from the backup that your module was creating, the right module order was again ok.

After that i put the “MMM-Mobile” module at first module in my config and my mirror works like before.

**Comment by fewieden** [comment]
Currently the config gets saved into one line, this will be adressed in the next version. The order of the modules get sorted by region (to let the user easily reorder modules in the app), but still remain in the same order of display. Is there any issue with reordering I should know about?
