### ISSUE TITLE
"Skip" text on initial loading screens has a slight overlap with iOS status bar

### ISSUE THREAD

**Issue by morozgrafix** [fewieden/MMM-Mobile#4]
iPhone 6S iOS 10.2 (14C92)

3 initial screen after launching the app have "Skip" text/button in the top right corner. Text "Skip" slightly overlaps with battery level of the iOS top status bar. Screenshot is attached. Thanks.

![image](https://cloud.githubusercontent.com/assets/1007608/21785247/a85a3496-d673-11e6-82e7-feab90fcb050.png)

**Comment by fewieden** [comment]
Fixed in the upcoming version, which will hide the statusbar completely for the tour
