### ISSUE TITLE
Cannot connect to Magic Mirror

### ISSUE THREAD

**Issue by in-a-days** [fewieden/MMM-Mobile#6]
I am able to install the app and load the module.  It sure looks like my phone is successfully scanning the QR code.  There's a small message that pops up on the bottom "found plain text:" and it proceeds to the Modules screen.  When I click "Sync" I get an error "Can not connect to Magic Mirror" and the app freezes with the "sync" message on the screen.

I am running Android version 6.0.1.

**Comment by fewieden** [comment]
Important: With sync you send data to the mirror, you have pull-to-refresh to get data from the mirror.

I will investigate the freeze

**Comment by in-a-days** [comment]
Thank you.  I am able to pull-to-refresh, but I don't see any sign of data from my mirror.  The app shows no modules installed, and gives me no option to install the modules listed as available.

**Comment by fewieden** [comment]
Check your messages on the forum, so we can investigate this together

**Comment by fewieden** [comment]
Problem was the hostname of the rpi was not mapped in the network, don't know where the problem relies on. Next version will use hostname by default or ip configurable via config

**Comment by mridl200** [comment]
Is there a manual fix we can use in the meantime?

**Comment by in-a-days** [comment]
@fewieden has gone to bed, but I can share the solution that got me connected.  

You need to edit modules/MMM-Mobile/node_helper.js.  And add the local IP address of your Mirror.

Find this line.

host: os.hostname(),

And replace os.hostname(), with '192.168.x.x', (using the real local address of your mirror),

It needs to be wrapped with ' ' and to close with a comma.

After this configuration change you will probably need to generate a new QR code to sync your phone app.  Navagate to MagicMirror/modules/MMM-Mobile and 

rm mobile.json
rm qr.png

This should generate a new QR code the next time you start your mirror.  Scan the QR code with the app, then go to Regions and pull to refresh.  If you can see the Region list you have successfully connected.  Next go to Modules and again, pull to refresh.  If you miss the QR code you can always delete those two files and try again.

**Comment by in-a-days** [comment]
Following up, I found some resources that indicate the regular PI install is not 'discoverable' to Windows networks with the stock configuration.  I followed these directions to install Samba, and I can now ping the PI hostname and get a response, but it still doesn't seem to access via browser (and os.hostname() still doesn't work).  I also don't know if these Windows issues would translate to the Android OS running on my mobile device.

http://blogs.arcsoftwareconsultancy.com/pi/2013/03/07/windows-networking/

**Comment by mridl200** [comment]
Thank you for the follow up.  I was able to get two numbers from 'sudo ip addr show' but so far neither has worked.  Now that you have pointed me in a direction though I can try and troubleshoot the rest.  Thanks again!

**Comment by in-a-days** [comment]
From within addr show, it depends on whether you are connected via ethernet or Wifi.  Ethernet is eth0, wifi is wlan0.

Mine looks like this:

...

2: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether b8:27:eb:ae:e2:07 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::7bcb:4435:e210:dc0f/64 scope link tentative
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:fb:b7:52 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.107/24 brd 192.168.0.255 scope global wlan0


I'm connected via wlan0 so the number between 'inet' and '/24' is what I need.  In this case, 192.168.0.107.

So the call in my node_helper.js is:

host: '192.168.0.107',

**Comment by mridl200** [comment]
Yea that's what i'd figured.  I went with 192.168.0.10.  When I scan the QR now it will say that it is reading from there, but the result is the same.

**Comment by in-a-days** [comment]
Try re-installing the app, and re-generating the QR code.  If that does not work I'm sure @fewieden will be happy to help you troubleshoot very soon.

**Comment by mridl200** [comment]
Appreciate the help from both of you :)

Edit: My mobile.json file does show all the installed modules that I have.  So the pairing is working but nothing is being displayed.

**Comment by fewieden** [comment]
Are you using v2.1.0 of the MagicMirror? If so did you try to access the mirror from an browser of another computer (IP:PORT; 192.168.0.10:8080), maybe you have an issue with the ipwhitelist feature.

The magic mirror module is checking the modules also if you are not paired.

You can also send me a pm on the forum and we can start a remote desktop session to investigate this further.

**Comment by fewieden** [comment]
There is now a config option for using the ip
